Repository FEeasy404/GameUs, pull requests merged in 2022-08, with the labels that each got.

#190 Docs: README.md 발표자료 내용으로 수정
  README.md
Labels: 📝docs

#189 Fix: 프로필 수정 시 기존의 데이터를 불러오도록 수정
  src/common/BASE_IMAGE.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPageAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePageAPI.js
Labels: 🌿Priority: Low, ⚔Fix

#191 Feat: 회원 가입 페이지에 비밀번호 확인 추가
  src/components/modules/LoginForm/LoginForm.jsx
  src/pages/RegisterPage/RegisterPage.jsx
Labels: ✨Feat, 🖐Priority: Medium, ⚔Fix

#192 Rename: 컴포넌트 이름 및 경로 변경
  src/components/atoms/MyChat/MyChat.jsx
  src/components/atoms/MyChat/mychat.module.css
  src/components/atoms/UserChat/UserChat.jsx
  src/components/atoms/UserChat/userchat.module.css
  src/components/modules/ChatRoom/ChatRoom.jsx
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/ProductCard/ProductCard.jsx
  src/components/modules/ProductCard/productCard.module.css
  src/components/organisms/ProductList/ProductList.jsx
Labels: 🌿Priority: Low, ⚔Fix

#195 Fix: 로그인 페이지의 버튼 비활성화 오류 수정
  src/components/molecules/LoginForm/LoginForm.jsx
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#196 Fix: 팔로우/언팔로우 시 딜레이가 있던 현상 수정
  src/common/FollowUser.js
  src/common/UnfollowUser.js
  src/components/molecules/ProfileButton/ProfileButton.jsx
  src/components/molecules/UserFollow/UserFollow.jsx
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#197 Fix: 타인의 프로필 페이지에서 하단 바의 프로필 버튼을 눌렀을 때의 오류 수정
  src/components/atoms/NavItem/NavItem.jsx
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#198 Fix: 컨텍스트에 정보 저장하기 전 토큰 검증하도록 수정
  src/common/checkValid.js
  src/components/molecules/LoginForm/LoginForm.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: 🚨Priority: High, ⚔Fix

#199 Design: PostCard 컴포넌트의 프로필 사진 링크 범위 수정
  src/components/molecules/PostCard/postCard.module.css
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#200 Feat & Fix: favicon 추가 및 index.html의 타이틀 수정
  public/favicon.ico
  public/index.html
Labels: ✨Feat, 🌿Priority: Low, ⚔Fix

#201 Docs: 리드미 정렬 수정 및 내용 개선
  README.md
Labels: 📝docs

#202 Fix: Post view 페이지 및 댓글 컴포넌트 오류 수정
  src/components/atoms/SignInSignUp/SignInSignUp.jsx
  src/components/atoms/SignInSignUp/signInSignUp.module.css
  src/components/molecules/HeaderForm/headerForm.module.css
  src/components/molecules/MessageInput/MessageInput.jsx
  src/components/organisms/CommentList/CommentList.jsx
  src/pages/PostViewPage/PostViewPage.jsx
  src/pages/PostViewPage/PostViewPageAPI.js
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#204 Feat: Search page 검색기능 추가
  src/components/atoms/HeaderInput/HeaderInput.jsx
  src/components/molecules/HeaderForm/HeaderForm.jsx
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/molecules/SearchCard/searchCard.module.css
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/SearchPageAPI.js
  src/pages/SearchPage/searchPage.module.css
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#206 Fix: App.jsx에서 토큰 유효성 검사하도록 수정
  src/App.jsx
Labels: 🚨Priority: High, ⚔Fix

#207 Feat: 좋아요 기능 추가
  src/components/atoms/Like/Like.jsx
  src/components/atoms/Like/도전_Like.jsx
  src/components/molecules/PostCard/PostCardAPI.js
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#208 Style: import 문 순서 변경 및 정리
  src/App.jsx
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Comment/Comment.jsx
  src/components/atoms/HeaderInput/HeaderInput.jsx
  src/components/atoms/IconButton/IconButton.jsx
  src/components/atoms/ImageInputButton/ImageInputButton.jsx
  src/components/atoms/Like/Like.jsx
  src/components/atoms/MyChat/MyChat.jsx
  src/components/atoms/NavItem/NavItem.jsx
  src/components/atoms/TextArea/TextArea.jsx
  src/components/atoms/UserChat/UserChat.jsx
  src/components/molecules/BottomNavigateBar/BottomNavigateBar.jsx
  src/components/molecules/ChatRoom/ChatRoom.jsx
  src/components/molecules/CommentForm/CommentForm.jsx
  src/components/molecules/HeaderForm/HeaderForm.jsx
  src/components/molecules/ImageInputForm/ImageInputForm.jsx
  src/components/molecules/ImagePostCard/ImagePostCard.jsx
  src/components/molecules/InfoIconGroup/InfoIconGroup.jsx
  src/components/molecules/Loading/Loading.jsx
  src/components/molecules/LoginForm/LoginForm.jsx
  src/components/molecules/MessageInput/MessageInput.jsx
  src/components/molecules/ModalNormal/ModalNormal.jsx
  src/components/molecules/ModalRequestion/ModalRequestion.jsx
  src/components/molecules/PostCard/PostCard.jsx
  src/components/molecules/ProductCard/ProductCard.jsx
  src/components/molecules/ProductTextInput/ProductTextInput.jsx
  src/components/molecules/ProfileButton/ProfileButton.jsx
  src/components/molecules/ProfileForm/ProfileForm.jsx
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/molecules/UploadImage/UploadImage.jsx
  src/components/molecules/UploadText/UploadText.jsx
  src/components/molecules/UserFollow/UserFollow.jsx
  src/components/molecules/UserProfileBox/UserProfileBox.jsx
  src/components/organisms/AddProduct/AddProduct.jsx
  src/components/organisms/CommentList/CommentList.jsx
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/Modal/Modal.jsx
  src/components/organisms/PostList/PostList.jsx
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/components/organisms/UploadForm/UploadForm.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/font.css
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/pages/PostViewPage/PostViewPage.jsx
  src/pages/ProductEditPage/ProductEditPage.jsx
  src/pages/ProductUploadPage/ProductUploadPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: 🌿Priority: Low, ⚔Fix

#209 Docs: README.md 파일에 배포 링크 추가 및 내용 수정
  README.md
Labels: 📝docs, 🖐Priority: Medium

#211 Fix: 토큰 검증이 안 되었을 때 confirm 창 출력되게 수정
  src/App.jsx
  src/common/checkValid.js
Labels: 🚨Priority: High, ⚔Fix
