Repository FEeasy404/GameUs, pull requests merged in 2022-07, with the labels that each got.

#17 Feat: 버튼 컴포넌트 및 스타일시트 생성
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Button/Button.module.css
  src/components/atoms/test.txt
Labels: ✨new feature, 🖐Priority: Medium

#18 Feat : 로그인 폼 모듈 생성
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Button/button.css
  src/components/modules/LoginForm/LoginForm.jsx
Labels: ✨new feature, 🖐Priority: Medium

#20 Feature: 로그인 폼 올가니즘화 및 로그인, 회원가입 페이지 구현 #4
  public/reset.css
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/test.txt
  src/components/organisms/LoginPageForm/LoginPageForm.jsx
  src/components/organisms/test.txt
  src/index.js
  src/pages/JoinPage.jsx
  src/pages/LoginPage.jsx
  src/pages/test.txt
Labels: ✨new feature, 🖐Priority: Medium

#19 Feat: 로그인, 회원가입 이동 링크 버튼 생성 #4
  src/components/atoms/SignInSignUp/SignInSignUp.jsx
  src/components/atoms/SignInSignUp/signInSignUp.module.css
Labels: ✨new feature, 🖐Priority: Medium

#21 Fix: reset.css가 하위 페이지에서 적용되지 않던 오류 수정
  public/index.html
  src/app.css
  src/components/organisms/LoginPageForm/LoginPageForm.jsx
  src/reset.css
Labels: 🐛bug, 🖐Priority: Medium

#22 프로필 설정 페이지 생성
  src/components/atoms/ProfileImageInput/ProfileImageInput.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/ProfileSettingPage.jsx
Labels: ✨new feature, 🖐Priority: Medium

#23 Design: .max-width wrapper를 App.jsx에서 감싸주도록 변경
  src/App.js
  src/App.jsx
  src/components/organisms/LoginPageForm/LoginPageForm.jsx
Labels: ✨new feature, 🖐Priority: Medium

#24 Rename, Feature: 입력 폼 컴포넌트 이름변경, 상품등록 모듈 생성
  src/components/atoms/InputBox/InputBox.jsx
  src/components/atoms/InputBox/inputBox.module.css
  src/components/atoms/LoginInput/LoginInput.jsx
  src/components/modules/ProductTextInput/ProductTextInput.jsx
Labels: ✨new feature, 🖐Priority: Medium

#26 이미지 파일 업로드 인풋 컴포넌트 생성
  src/assets/icon-image.svg
  src/assets/test.txt
  src/components/atoms/ImageInput/ImageInput.jsx
  src/components/atoms/ImageInput/imageinput.module.css
  src/components/atoms/ProfileImageInput/ProfileImageInput.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
Labels: ✨new feature, 🖐Priority: Medium

#25 Feature: Image 컴포넌트 및 스타일시트 생성
  src/components/atoms/Image/Image.jsx
  src/components/atoms/Image/image.module.css
Labels: ✨new feature, 🖐Priority: Medium

#28 Fix: InputBox 컴포넌트명 미변경 파일 수정
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
Labels: 🐛bug, 🌿Priority: Low

#29 Design: 로그인, 회원가입 페이지 css 구현
  src/App.jsx
  src/components/atoms/InputBox/InputBox.jsx
  src/components/atoms/InputBox/inputBox.module.css
  src/components/organisms/EmailPasswordForm/EmailPasswordForm.jsx
  src/components/organisms/EmailPasswordForm/emailPasswordForm.module.css
  src/components/organisms/LoginPageForm/LoginPageForm.jsx
  src/global.css
  src/pages/JoinPage.jsx
  src/pages/LoginPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/loginPage.module.css
Labels: ✨new feature, 🖐Priority: Medium

#30 Button 컴포넌트 css 모듈화
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Button/button.module.css
Labels: ✨new feature, 🖐Priority: Medium

#31 Rename: 이미지 파일 컴포넌트 이름 변경 및 클래스명 변경
  src/components/atoms/ImageBox/ImageBox.jsx
  src/components/atoms/ImageBox/imageBox.module.css
Labels: 🖐Priority: Medium

#36 Feat: 팔로우/팔로잉 유저 정보를 보여주는 UserFollow 컴포넌트 및 css 구현
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/modules/UserFollow/UserFollow.jsx
  src/components/modules/UserFollow/userFollow.module.css
Labels: ✨new feature, 🖐Priority: Medium

#37 Style: 색상 변수화 및 색상 변수를 css파일에 일괄 적용
  src/components/atoms/Button/button.module.css
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/atoms/ImageInputButton/imageInputButton.module.css
  src/components/atoms/InputBox/inputBox.module.css
  src/components/atoms/SignInSignUp/signInSignUp.module.css
  src/components/atoms/UserInfo/userInfo.module.css
  src/components/atoms/UserNameIntroduce/userNameIntroduce.module.css
  src/components/modules/ImageInputForm/imageInputForm.module.css
  src/components/organisms/EmailPasswordForm/emailPasswordForm.module.css
  src/global.css
  src/pages/LoginPage/loginPage.module.css
Labels: ✨new feature, 🖐Priority: Medium

#38 Feat: Header 모듈 생성
  src/assets/icon-arrow-left.svg
  src/assets/icon-more-vertical.svg
  src/assets/icon-search.svg
  src/components/atoms/HeaderInput/HeaderInput.jsx
  src/components/atoms/HeaderInput/headerInput.module.css
  src/components/atoms/IconButton/IconButton.jsx
  src/components/atoms/IconButton/IconButton.module.css
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/HeaderForm/headerForm.module.css
  src/global.css
Labels: ✨new feature, 🖐Priority: Medium

#39 Feat: 팔로워/팔로잉 수를 나타내는 컴포넌트 및 css 구현
  src/components/atoms/NumberFollow/NumberFollow.jsx
  src/components/atoms/NumberFollow/numberFollow.module.css
Labels: ✨new feature, 🖐Priority: Medium

#40 Feat: 유저 정보, 팔로워/팔로잉 수, 프로필 사진을 결합한 컴포넌트 및 css 구현
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/modules/UserProfileBox/UserProfileBox.jsx
  src/components/modules/UserProfileBox/userProfileBox.module.css
Labels: ✨new feature, 🖐Priority: Medium

#41 Feat: 유저 프로필 하단의 버튼이 결합된 컴포넌트 구현
  src/assets/icon-message-circle.svg
  src/assets/icon-share.svg
  src/components/atoms/IconButton/IconButton.jsx
  src/components/atoms/IconButton/IconButton.module.css
  src/components/modules/MyProfileButton/MyProfileButton.jsx
  src/components/modules/MyProfileButton/myProfileButton.module.css
  src/components/modules/ProfileButton/ProfileButton.jsx
  src/components/modules/ProfileButton/profileButton.module.css
Labels: ✨new feature, 🖐Priority: Medium

#43 홈 피드 게시글카드 하단의 게시글 정보 컴포넌트
  src/assets/icon-like-empty.svg
  src/assets/icon-message.svg
  src/components/atoms/Comment/Comment.jsx
  src/components/atoms/Comment/comment.module.css
  src/components/atoms/Like/Like.jsx
  src/components/atoms/Like/like.module.css
  src/components/atoms/PostDate/PostDate.jsx
  src/components/atoms/PostDate/postDate.module.css
  src/components/modules/InfoIconGroup/InfoIconGroup.jsx
  src/components/modules/InfoIconGroup/infoIconGroup.module.css
Labels: ✨new feature, 🖐Priority: Medium

#45 Rename: iconButton css 파일명 수정
  src/components/atoms/IconButton/iconButton.module.css
Labels: 🐛bug

#48 Feat: 판매 중인 상품 목록에 들어갈 상품 컴포넌트 및 css 구현
  src/components/modules/Product/Product.jsx
  src/components/modules/Product/product.module.css
Labels: ✨new feature, 🖐Priority: Medium

#46 Feat: 상품 등록 페이지 UI 완성
  src/App.jsx
  src/components/atoms/ImageInputButton/ImageInputButton.jsx
  src/components/atoms/ImageInputButton/imageInputButton.module.css
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/HeaderForm/headerForm.module.css
  src/components/modules/ProductTextInput/ProductTextInput.jsx
  src/components/organisms/AddProduct/AddProduct.jsx
  src/components/organisms/AddProduct/addProduct.module.css
  src/components/organisms/EmailPasswordForm/EmailPasswordForm.jsx
  src/global.css
  src/pages/AddProductPage.jsx
Labels: ✨new feature, 🖐Priority: Medium

#49 판매 중인 상품 리스트 컴포넌트 및 css 구현
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProductList/productList.module.css
Labels: ✨new feature, 🖐Priority: Medium

#50 Feat: 판매중인 상품 부분을 프로필 페이지에 추가 및 프로필 페이지에 ir 텍스트 삽입
  src/components/modules/MyProfileButton/MyProfileButton.jsx
  src/components/modules/UserProfileBox/UserProfileBox.jsx
  src/pages/ProfilePage.jsx
Labels: ✨new feature, 🌿Priority: Low

#52 Feat: 상품 업로드 페이지 UI 완성
  src/App.jsx
  src/assets/x.svg
  src/components/atoms/IconButton/iconButton.module.css
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/atoms/ImageInputButton/ImageInputButton.jsx
  src/components/modules/ImageInputForm/ImageInputForm.jsx
  src/components/modules/PostImage/PostImage.jsx
  src/components/modules/PostImage/postImage.module.css
  src/components/organisms/PostForm/PostForm.jsx
  src/components/organisms/PostForm/postForm.module.css
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/uploadPage.module.css
Labels: ✨new feature, 🖐Priority: Medium

#53 Feat: 포스트 페이지, 채팅 페이지 하단 댓글, 채팅 입력 모듈 컴포넌트 UI 생성
  src/components/modules/MessageInput/MessageInput.jsx
  src/components/modules/MessageInput/messageInput.module.css
Labels: ✨new feature, 🖐Priority: Medium

#56 게시글 카드 댓글 및 게시글에 사용되는 더보기 버튼 컴포넌트 생성
  package-lock.json
  src/assets/icon-more-vertical-small.svg
  src/components/atoms/Author/Author.jsx
  src/components/atoms/Author/author.module.css
  src/components/atoms/MoreButton/MoreButton.jsx
  src/components/atoms/MoreButton/moreButton.module.css
Labels: ✨new feature, 🖐Priority: Medium

#57 Feat: fetch를 사용하여 서버에서 프로필 데이터를 받아오도록 변경
  src/App.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/ProfilePage.jsx
Labels: ✨new feature, 🚨Priority: High

#59 Feat: 팔로워/팔로잉 페이지 구현
  src/App.jsx
  src/components/atoms/NumberFollow/NumberFollow.jsx
  src/components/modules/HeaderForm/headerForm.module.css
  src/components/modules/Product/Product.jsx
  src/components/modules/UserFollow/UserFollow.jsx
  src/components/modules/UserFollow/userFollow.module.css
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/FollowList/followList.module.css
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProductList/productList.module.css
  src/pages/FollowerPage.jsx
  src/pages/FollowingPage.jsx
  src/pages/ProfilePage.jsx
Labels: ✨new feature, 🚨Priority: High

#62 Fix: InputBox 컴포넌트명 미변경 재수정
  src/components/atoms/InputBox/InputBox.jsx
Labels: 🐛bug, 🚨Priority: High

#63 Fix: ProfileForm의 InputBox 컴포넌트에 placeholder 추가
  src/components/modules/ProfileForm/ProfileForm.jsx
Labels: 🌿Priority: Low

#64 Feat: 프로필 수정 페이지 마크업 및 css 구현
  src/App.jsx
  src/components/modules/MyProfileButton/MyProfileButton.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/modules/ProfileForm/profileForm.module.css
  src/pages/ProfileEditPage.jsx
Labels: ✨new feature, 🖐Priority: Medium

#65 Feat: 상품 등록 페이지 상품 등록 기능 추가
  package-lock.json
  package.json
  src/App.jsx
  src/components/atoms/Button/button.module.css
  src/components/atoms/ImageInputButton/ImageInputButton.jsx
  src/components/atoms/InputBox/InputBox.jsx
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/ImageInputForm/ImageInputForm.jsx
  src/components/modules/ProductTextInput/ProductTextInput.jsx
  src/components/organisms/AddProduct/AddProduct.jsx
  src/pages/AddProductPage.jsx
Labels: 🚀API, 🖐Priority: Medium

#66 Feat: Upload page 텍스트, 이미지 업로드 기능 구현
  src/App.jsx
  src/components/atoms/TextArea/TextArea.jsx
  src/components/modules/UploadText/UploadText.jsx
  src/components/organisms/UploadForm/UploadForm.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🚀API, 🖐Priority: Medium

#67 Feat: 로그인 기능 구현 및 accountname으로 로그인한 계정 판별
  src/App.jsx
  src/components/atoms/InputBox/InputBox.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/AddProductPage.jsx
  src/pages/ProfilePage.jsx
Labels: ✨Feat, 🚨Priority: High, ⚔Fix

#68 Style: 로그인 핸들러 함수명 수정 및 accountname 수정
  src/App.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#70 Fix: 팔로워/팔로잉 목록에서 불러오는 인원 수의 제한 해제
  src/pages/FollowerPage.jsx
  src/pages/FollowingPage.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#71 Feat: 홈 피드 페이지 루트 연결 및 게시글 목록 API 생성
  src/App.jsx
  src/assets/icon-404-cat.png
  src/assets/icon-like-empty.svg
  src/assets/icon-like.svg
  src/assets/icon-user-2x.png
  src/assets/icon-user-fill-2x.png
  src/components/atoms/Author/author.module.css
  src/components/atoms/Like/like.module.css
  src/components/atoms/MoreButton/MoreButton.jsx
  src/components/atoms/MoreButton/moreButton.module.css
  src/components/atoms/PostDate/PostDate.jsx
  src/components/atoms/PostDate/postDate.module.css
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/postCard.module.css
  src/pages/HomePage.jsx
Labels: 🚀API, ✨Feat, 🚨Priority: High

#72 Feat: HomePage.jsx에서 받아온 게시글 데이터를 하위 컴포넌트로 전달
  src/components/atoms/Like/Like.jsx
  src/components/atoms/Like/도전_Like.jsx
  src/components/modules/InfoIconGroup/InfoIconGroup.jsx
  src/components/modules/PostCard/PostCard.jsx
  src/pages/HomePage/HomePage.jsx
Labels: ✨Feat, 🖐Priority: Medium

#77 Fix: 게시글에 이미지가 개수만큼 출력되게 수정
  src/components/modules/PostCard/PostCard.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🐛bug, ✨Feat, 🖐Priority: Medium

#78 Fix: 이미지 url을 콤마로만 구분하도록 변경
  src/pages/HomePage/HomePage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🌿Priority: Low, ⚔Fix

#79 Feat: 검색 페이지 UI 마크업, 라우터 연결
  src/App.jsx
  src/auth/test.txt
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/searchPage.module.css
  src/services/test.txt
Labels: ✨Feat, 🖐Priority: Medium

#81 Feat: Post 상세보기 페이지 post 데이터 및 댓글 데이터 불러오기 기능 추가
  src/App.jsx
  src/components/atoms/IconButton/iconButton.module.css
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/CommentForm/commentForm.module.css
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/InfoIconGroup/InfoIconGroup.jsx
  src/components/modules/MessageInput/messageInput.module.css
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/postCard.module.css
  src/components/organisms/CommentList/CommentList.jsx
  src/components/organisms/CommentList/commentList.module.css
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage.jsx
Labels: 🚀API, ✨Feat, 🖐Priority: Medium, ⚔Fix

#85 Feat: 404 페이지 마크업 및 기능 구현
  src/App.jsx
  src/assets/icon-404.svg
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/errorPage.module.css
Labels: ✨Feat, 🖐Priority: Medium

#84 Design: Header 컴포넌트를 fixed로 고정
  src/components/modules/HeaderForm/headerForm.module.css
  src/global.css
Labels: 🌿Priority: Low, ⚔Fix

#87 Feat: 댓글 추가 기능 구현
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/MessageInput/MessageInput.jsx
  src/components/organisms/CommentList/CommentList.jsx
  src/pages/PostPage.jsx
Labels: 🚀API, ✨Feat, 🖐Priority: Medium

#86 Fix: 게시글 컴포넌트(PostCard) 전달 props 및 스타일 수정
  src/components/atoms/Author/Author.jsx
  src/components/atoms/Comment/Comment.jsx
  src/components/atoms/MoreButton/MoreButton.jsx
  src/components/atoms/MoreButton/moreButton.module.css
  src/components/modules/InfoIconGroup/infoIconGroup.module.css
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/postCard.module.css
Labels: 🖐Priority: Medium, ⚔Fix

#89 Feat: 채팅목록 페이지 마크업 구현
  src/App.jsx
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/ChatListPage/chatListPage.module.css
Labels: ✨Feat, 🚨Priority: High

#82 Feat: 회원가입 유효성 검사 구현
  src/App.jsx
  src/components/atoms/InputBox/InputBox.jsx
  src/components/atoms/NumberFollow/NumberFollow.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/modules/ProfileForm/profileForm.module.css
  src/components/organisms/EmailPasswordForm/EmailPasswordForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/components/organisms/ProfileSetting/profileSetting.module.css
  src/contexts/RegisterContext.jsx
  src/pages/JoinPage.jsx
  src/pages/ProfileSettingPage.jsx
  src/pages/RegisterPage.jsx
Labels: 🚀API, ✨Feat, 🚨Priority: High

#92 Design: 전체 페이지 스크롤바 custom
  src/global.css
Labels: 🌿Priority: Low, ⚔Fix

#95 Fix: ImageBox 작은 이미지 깨짐 현상 수정
  src/components/atoms/ImageBox/imageBox.module.css
Labels: 🌿Priority: Low, ⚔Fix

#96 Design: 로그인, 회원가입 페이지의 컴포넌트 간의 간격 수정
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/LoginForm/loginForm.module.css
  src/pages/LoginPage/loginPage.module.css
Labels: 🌿Priority: Low, ⚔Fix

#97 Desing: Upload 페이지 UI 개선
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/atoms/TextArea/textArea.module.css
  src/components/modules/UploadText/uploadText.module.css
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/uploadPage.module.css
Labels: 🌿Priority: Low, ⚔Fix

#102 Refactor: 로그인, 회원가입의 state 통합 및 함수명 직관적으로 변경
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#101 Design: PostCard 게시물 작성 유저 이미지 추가
  src/components/atoms/Comment/Comment.jsx
  src/components/atoms/PostDate/PostDate.jsx
  src/components/modules/PostCard/PostCard.jsx
Labels: 🌿Priority: Low, ⚔Fix

#103 Design: 프로필 페이지의 버튼 css 수정 및 마크업 수정
  src/components/modules/MyProfileButton/myProfileButton.module.css
  src/components/modules/UserProfileBox/userProfileBox.module.css
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/components/organisms/UserProfile/userProfile.module.css
Labels: 🌿Priority: Low, ⚔Fix

#104 Feat: 팔로우 버튼을 클릭하면 팔로우/언팔로우로 바뀌도록 구현
  src/components/modules/ProfileButton/ProfileButton.jsx
  src/components/modules/ProfileButton/profileButton.module.css
Labels: ✨Feat, 🌿Priority: Low

#105 Docs: 여다희 역할분담 내용 추가
  README.md
Labels: 📝docs, 🌿Priority: Low

#110 Refactor: 페이지 API들, 이미지 업로드 및 리사이즈 함수 분리
  src/App.jsx
  src/common/ImageResize.js
  src/common/ImageUpload.js
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/atoms/ImageInputButton/ImageInputButton.jsx
  src/components/modules/ImageInputForm/ImageInputForm.jsx
  src/components/modules/ImageInputForm/imageInputForm.module.css
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/AddProductPageAPI.js
  src/pages/PostPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPageAPI.js
  src/pages/UploadPage/UploadAPI.js
  src/pages/UploadPage/UploadPage.jsx
Labels: 🌿Priority: Low, 👏Refactor

#112 Fix: 리팩토링 하다가 생긴 오류 개선
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/AddProductPageAPI.js
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/uploadPage.module.css
Labels: 🐛bug, ⚔Fix

#111 Docs: Readme 템플릿 작성 및 역할분담 추가
  README.md
Labels: 📝docs

#115 Fix: 게시글에서 유저 영역 클릭 시 이동하는 링크 수정
  src/components/atoms/Author/Author.jsx
  src/components/modules/PostCard/PostCard.jsx
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#113 Feat: Modal 기능 구현
  public/index.html
  src/assets/icon-modal-line.svg
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/ModalNormal/ModalNormal.jsx
  src/components/modules/ModalNormal/modalNormal.module.css
  src/components/modules/ModalRequestion/ModalRequestion.jsx
  src/components/modules/ModalRequestion/modalRequestion.module.css
  src/components/modules/PostCard/PostCard.jsx
  src/components/organisms/Modal/Modal.jsx
  src/components/organisms/Modal/modal.module.css
Labels: ✨Feat, 🚨Priority: High

#118 Fix: 이미지 post 갯수 제한 오류 수정
  src/pages/UploadPage/UploadPage.jsx
Labels: 🐛bug, ⚔Fix

#120 Fix: 게시글 업로드 시 이미지가 없어도 버튼 활성화되게 수정
  src/pages/UploadPage/UploadAPI.js
  src/pages/UploadPage/UploadPage.jsx
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#114 Feat: 하단 탭 메뉴 구현
  src/components/atoms/NavItem/NavItem.jsx
  src/components/atoms/NavItem/navItem.module.css
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
  src/components/modules/BottomNavigateBar/bottomNavigateBar.module.css
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/FollowerPage.jsx
  src/pages/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨Feat, 🚨Priority: High

#116 Feat: 프로필 페이지에 게시글 목록 추가
  src/App.jsx
  src/assets/icon-image-layers.svg
  src/assets/icon-post-album-off.svg
  src/assets/icon-post-album-on.svg
  src/assets/icon-post-list-off.svg
  src/assets/icon-post-list-on.svg
  src/components/atoms/IconButton/IconButton.jsx
  src/components/atoms/IconButton/iconButton.module.css
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
  src/components/modules/ImagePostCard/ImagePostCard.jsx
  src/components/modules/ImagePostCard/imagePostCard.module.css
  src/components/modules/PostHeader/PostHeader.jsx
  src/components/modules/PostHeader/postHeader.module.css
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/FollowerPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/profilePage.module.css
  src/pages/SearchPage/SearchPage.jsx
Labels: 🚀API, 🤔question, ✨Feat, 🖐Priority: Medium

#123 Fix: 팔로워/팔로잉 페이지의 레이아웃 오류 수정
  src/components/atoms/UserNameIntroduce/UserNameIntroduce.jsx
  src/components/atoms/UserNameIntroduce/userNameIntroduce.module.css
  src/components/modules/UserFollow/UserFollow.jsx
  src/components/modules/UserFollow/userFollow.module.css
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/FollowList/followList.module.css
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#125 Design: 글로벌 폰트 적용
  src/App.jsx
  src/assets/font/SpoqaHanSansNeo/LICENSE
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.eot
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.otf
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.eot
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.otf
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.eot
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.otf
  src/assets/font/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff
  src/components/modules/HeaderForm/headerForm.module.css
  src/font.css
  src/global.css
  src/reset.css
Labels: ✨Feat, 🌿Priority: Low

#122 Refactor: 이미지 업로드 함수 중복 코드 제거
  src/common/ImageUpload.js
  src/pages/UploadPage/UploadAPI.js
  src/pages/UploadPage/UploadPage.jsx
Labels: 🌿Priority: Low, 👏Refactor

#126 Fix: 하단바 프로필 클릭 시 로컬에 저장된 accountname의 프로필로 이동
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
Labels: 🚨Priority: High, ⚔Fix

#128 Feat: 나의 프로필 페이지에서 상품 누르면 모달 뜨는 기능 추가
  src/components/modules/Product/Product.jsx
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProductList/productList.module.css
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨Feat, 🖐Priority: Medium

#129 Refactor: BASE_URL 별도 파일로 분리
  src/common/BASE_URL.jsx
  src/common/ImageUpload.js
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/AddProductPage/AddProductPageAPI.js
  src/pages/FollowerPage.jsx
  src/pages/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage/PostPageAPI.js
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/UploadPage/UploadAPI.js
Labels: 🖐Priority: Medium, ⚔Fix

#130 Feat: 로그아웃 기능 추가
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/pages/HomePage/HomePage.jsx
Labels: ✨Feat, 🖐Priority: Medium

#131 Feat: 댓글 삭제 기능 추가 및 post 페이지 UI 수정
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/MessageInput/messageInput.module.css
  src/components/organisms/CommentList/CommentList.jsx
  src/global.css
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPageAPI.js
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#132 Refactor: 팔로워/팔로잉 페이지, 프로필 수정 페이지 API 분리
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/FollowerPage.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowerPage/FollowerPageAPI.js
  src/pages/FollowingPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/FollowingPage/FollowingPageAPI.js
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPageAPI.js
Labels: 🌿Priority: Low, ⚔Fix

#135 Refactor: 로그인/회원가입/프로필 페이지 API 분리
  src/App.jsx
  src/components/atoms/UserInfo/UserInfo.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/modules/UserProfileBox/UserProfileBox.jsx
  src/components/organisms/EmailPasswordForm/EmailPasswordForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/contexts/RegisterContext.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPageAPI.js
  src/pages/LoginPage/loginPage.module.css
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPageAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePageAPI.js
  src/pages/RegisterPage.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterPageAPI.js
Labels: 🌿Priority: Low, ⚔Fix, 👏Refactor

#136 Feat: Splash 페이지 추가
  src/App.jsx
  src/assets/background-splash.svg
  src/assets/button-splash.svg
  src/assets/logo-main.svg
  src/pages/HomePage/HomePage.jsx
  src/pages/SplashPage/SplashPage.jsx
  src/pages/SplashPage/splashPage.module.css
Labels: ✨Feat, 🖐Priority: Medium

#133 Feat: ContextAPI 사용하여 현재 탭에 하이라이팅
  src/components/atoms/NavItem/NavItem.jsx
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
Labels: 🤔question, 🖐Priority: Medium, ⚔Fix

#134 Feat: 게시물 삭제 기능 구현
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/PostCardAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🚀API, ✨Feat, 🖐Priority: Medium

#138 Feat: 로그인/회원가입/프로필 수정을 엔터로도 실행되게 하는 기능 추가
  src/components/atoms/InputBox/InputBox.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
Labels: 🤔question, ✨Feat, 🌿Priority: Low

#141 Design: body에 주는 padding을 wrapper-contents 클래스를 통해 컨트롤하도록 변경
  src/global.css
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#143 Feat: 상품 삭제 기능 추가
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProductList/ProductListAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#151 Fix: 피드, 팔로워/팔로잉, 프로필 페이지에서 데이터를 불러올 때 깜빡이는 오류 수정
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#150 Design: 패딩 삭제 후의 패딩값 변경 및 이미지 비율 조절
  src/components/atoms/ImageBox/imageBox.module.css
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/FollowList/followList.module.css
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/profileEditPage.module.css
  src/pages/SplashPage/splashPage.module.css
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#155 Fix: 각 페이지 h1 태그를 h2 태그로 변경
  src/App.jsx
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/PostHeader/PostHeader.jsx
  src/components/organisms/EmailPasswordForm/EmailPasswordForm.jsx
  src/components/organisms/ProfileSetting/ProfileSetting.jsx
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/ChatListPage/ChatListPage.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SplashPage/SplashPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🖐Priority: Medium, ⚔Fix

#154 Fix: 화면이 좁아질 때 하단 탭 "게시글 추가"가 줄바꿈이 일어나는 현상 해결
  src/components/atoms/NavItem/NavItem.jsx
  src/components/atoms/NavItem/navItem.module.css
  src/components/modules/BottomNavigateBar/bottomNavigateBar.module.css
Labels: 🖐Priority: Medium, ⚔Fix

#152 Feat: 게시물 및 댓글 신고 기능 추가
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/ModalRequestion/ModalRequestion.jsx
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/PostCardAPI.js
  src/components/organisms/CommentList/CommentList.jsx
  src/components/organisms/Modal/Modal.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPageAPI.js
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#142 Feat: 채팅방 마크업 및 css 구현
  src/App.jsx
  src/components/atoms/Chat/MyChat/MyChat.jsx
  src/components/atoms/Chat/MyChat/mychat.module.css
  src/components/atoms/Chat/UserChat/UserChat.jsx
  src/components/atoms/Chat/UserChat/userchat.module.css
  src/components/modules/ChatRoom/ChatRoom.jsx
  src/components/modules/ChatRoom/chatroom.module.css
  src/pages/ChatRoomPage/ChatRoomPage.jsx
Labels: ✨Feat, 🖐Priority: Medium

#160 Design: 스플래시 화면 꽉채우기
  src/pages/SplashPage/splashPage.module.css
Labels: 🌿Priority: Low, ⚔Fix

#158 Fix: 로컬스토리지 대신 세션스토리지에 계정 정보 저장 및 프로필 사진 뜨도록 수정
  src/App.jsx
  src/common/ImageUpload.js
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/LoginForm/LoginForm.jsx
  src/components/modules/UploadText/UploadText.jsx
  src/contexts/LoginedUserContext.jsx
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/AddProductPageAPI.js
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowerPage/FollowerPageAPI.js
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/FollowingPage/FollowingPageAPI.js
  src/pages/HomePage/HomePage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostEditPage/PostEditPageAPI.js
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPageAPI.js
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPageAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePageAPI.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SplashPage/SplashPage.jsx
  src/pages/UploadPage/UploadAPI.js
  src/pages/UploadPage/UploadPage.jsx
Labels: 🌿Priority: Low, ⚔Fix

#165 Fix: 페이지 새로고침할 때 context 세팅이 안 되던 문제 수정
  src/App.jsx
  src/components/atoms/NavItem/navItem.module.css
  src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
  src/components/modules/CommentForm/CommentForm.jsx
  src/components/modules/HeaderForm/HeaderForm.jsx
  src/components/modules/PostCard/PostCard.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: 🐛bug, 🚨Priority: High

#169 Feat: 404 페이지에 메인 페이지로 가는 버튼 추가
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/errorPage.module.css
Labels: ✨Feat, 🌿Priority: Low

#170 Fix: 프로필 수정 후에도 기존 accountname과 비교하고 있던 오류 수정
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPageAPI.js
Labels: 🐛bug, 🖐Priority: Medium

#171 Fix: 상품/게시글 삭제 후 프로필 페이지가 업데이트되지 않던 문제 수정
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/PostCard/PostCardAPI.js
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/ProductList/ProductListAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🐛bug, 🖐Priority: Medium, ⚔Fix

#176 Feat: 팔로우/언팔로우 기능 추가
  src/common/FollowUser.js
  src/common/UnfollowUser.js
  src/components/modules/ProfileButton/ProfileButton.jsx
  src/components/modules/UserFollow/UserFollow.jsx
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
Labels: 🚀API, ✨Feat, 🚨Priority: High

#174 Refactor & Feat: 상품 업로드 페이지 리펙토링 및 상품 수정 페이지 생성
  src/App.jsx
  src/components/modules/CommentForm/commentForm.module.css
  src/components/modules/ProductTextInput/ProductTextInput.jsx
  src/components/organisms/AddProduct/AddProduct.jsx
  src/components/organisms/AddProduct/addProduct.module.css
  src/components/organisms/ProductList/ProductList.jsx
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/pages/PostUploadPage/PostUploadPageAPI.js
  src/pages/PostViewPage/PostViewPage.jsx
  src/pages/PostViewPage/PostViewPageAPI.js
  src/pages/ProductEditPage/ProductEditPage.jsx
  src/pages/ProductEditPage/ProductEditPageAPI.js
  src/pages/ProductUploadPage/ProductUploadPage.jsx
  src/pages/ProductUploadPage/ProductUploadPageAPI.js
Labels: 🚀API, ✨Feat, 🌿Priority: Low

#181 Design: 모바일에서 프로필 사진과 팔로워/팔로잉 수 사이의 간격이 줄어들게 수정
  src/components/modules/UserProfileBox/userProfileBox.module.css
Labels: 🌿Priority: Low, ⚔Fix

#178 Refactor: 프로필 페이지의 무한 리렌더링 수정
  src/components/modules/PostCard/PostCard.jsx
  src/components/modules/ProfileButton/ProfileButton.jsx
  src/components/modules/UserFollow/UserFollow.jsx
  src/components/organisms/FollowList/FollowList.jsx
  src/components/organisms/PostList/PostList.jsx
  src/components/organisms/PostList/postList.module.css
  src/components/organisms/ProductList/ProductList.jsx
  src/components/organisms/UserProfile/UserProfile.jsx
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowerPage/FollowerPageAPI.js
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/FollowingPage/FollowingPageAPI.js
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🐛bug, 🖐Priority: Medium, 👏Refactor

#179 Fix: Image box 경로 잘못되었을 경우 대체이미지 넣기
  src/components/atoms/ImageBox/ImageBox.jsx
  src/components/modules/PostCard/postCard.module.css
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#182 Feat: Loading 컴포넌트 생성
  src/components/modules/Loading/Loading.jsx
  src/components/modules/Loading/loading.module.css
  src/pages/HomePage/HomePage.jsx
  src/pages/PostViewPage/PostViewPage.jsx
Labels: ✨Feat, 🌿Priority: Low

#184 Feat: 프로필 페이지와 팔로워/팔로잉 페이지 로딩 기능 추가
  src/pages/FollowerPage/FollowerPage.jsx
  src/pages/FollowingPage/FollowingPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨Feat, 🌿Priority: Low

#183 Fix: 프로필의 소개 부분에 말줄임표 추가 및 20자로 제한
  src/components/atoms/UserInfo/UserInfo.jsx
  src/components/atoms/UserInfo/userInfo.module.css
  src/components/modules/ProfileForm/ProfileForm.jsx
  src/pages/RegisterPage/RegisterPage.jsx
Labels: 🐛bug, 🌿Priority: Low, ⚔Fix

#185 Fix: 존재하지 않는 사용자일 경우 에러 페이지를 보여주도록 수정
  src/components/atoms/NavItem/NavItem.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePageAPI.js
Labels: 🐛bug, 🤔question, 🖐Priority: Medium
